### ISSUE TITLE
touristes avec deux coupes de cheveux en même temps

### ISSUE THREAD

**Issue by TahitiP4ncake** [PlipPlopTeam/plipplop#7]
![image](https://user-images.githubusercontent.com/24491634/78874107-25e3a300-7a4c-11ea-869a-b51f62f06f7d.png)

**Comment by Barkintosh** [comment]
![Capture](https://user-images.githubusercontent.com/28601638/78883273-95ac5a80-7a59-11ea-8d48-13c456720257.PNG)
